//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace EldigmPlusApp.WsSCodeGrp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWsSysCodeGrp", Namespace="http://tempuri.org/")]
    public partial class WsSysCodeGrp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sSysCodeGrpOperationCompleted;
        
        private System.Threading.SendOrPostCallback mSysCodeGrpOperationCompleted;
        
        private System.Threading.SendOrPostCallback sSysCodeGrp_UsingFlagOperationCompleted;
        
        private System.Threading.SendOrPostCallback sSysCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback mSysCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback exSysCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback aSysCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback fSysCodeSearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsSysCodeGrp() {
            this.Url = global::EldigmPlusApp.Properties.Settings.Default.EldigmPlusApp_WsSCodeGrp_WsSysCodeGrp;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sSysCodeGrpCompletedEventHandler sSysCodeGrpCompleted;
        
        /// <remarks/>
        public event mSysCodeGrpCompletedEventHandler mSysCodeGrpCompleted;
        
        /// <remarks/>
        public event sSysCodeGrp_UsingFlagCompletedEventHandler sSysCodeGrp_UsingFlagCompleted;
        
        /// <remarks/>
        public event sSysCodeCompletedEventHandler sSysCodeCompleted;
        
        /// <remarks/>
        public event mSysCodeCompletedEventHandler mSysCodeCompleted;
        
        /// <remarks/>
        public event exSysCodeCompletedEventHandler exSysCodeCompleted;
        
        /// <remarks/>
        public event aSysCodeCompletedEventHandler aSysCodeCompleted;
        
        /// <remarks/>
        public event fSysCodeSearchCompletedEventHandler fSysCodeSearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsSysCodeGrp/sSysCodeGrp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sSysCodeGrp([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScodeGrp, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Memco.WebSvc.Sys.SysCode")] out DataSysCodeGrp[] reList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg) {
            object[] results = this.Invoke("sSysCodeGrp", new object[] {
                        pScodeGrp});
            reList = ((DataSysCodeGrp[])(results[1]));
            reMsg = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sSysCodeGrpAsync(string pScodeGrp) {
            this.sSysCodeGrpAsync(pScodeGrp, null);
        }
        
        /// <remarks/>
        public void sSysCodeGrpAsync(string pScodeGrp, object userState) {
            if ((this.sSysCodeGrpOperationCompleted == null)) {
                this.sSysCodeGrpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsSysCodeGrpOperationCompleted);
            }
            this.InvokeAsync("sSysCodeGrp", new object[] {
                        pScodeGrp}, this.sSysCodeGrpOperationCompleted, userState);
        }
        
        private void OnsSysCodeGrpOperationCompleted(object arg) {
            if ((this.sSysCodeGrpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sSysCodeGrpCompleted(this, new sSysCodeGrpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsSysCodeGrp/mSysCodeGrp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mSysCodeGrp([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScodeGrp, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScodeNm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pUsingFlag, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pSortNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pMemo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, out int reData, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool reDataSpecified) {
            object[] results = this.Invoke("mSysCodeGrp", new object[] {
                        pScodeGrp,
                        pScodeNm,
                        pUsingFlag,
                        pSortNo,
                        pMemo});
            reMsg = ((string)(results[1]));
            reData = ((int)(results[2]));
            reDataSpecified = ((bool)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void mSysCodeGrpAsync(string pScodeGrp, string pScodeNm, string pUsingFlag, string pSortNo, string pMemo) {
            this.mSysCodeGrpAsync(pScodeGrp, pScodeNm, pUsingFlag, pSortNo, pMemo, null);
        }
        
        /// <remarks/>
        public void mSysCodeGrpAsync(string pScodeGrp, string pScodeNm, string pUsingFlag, string pSortNo, string pMemo, object userState) {
            if ((this.mSysCodeGrpOperationCompleted == null)) {
                this.mSysCodeGrpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmSysCodeGrpOperationCompleted);
            }
            this.InvokeAsync("mSysCodeGrp", new object[] {
                        pScodeGrp,
                        pScodeNm,
                        pUsingFlag,
                        pSortNo,
                        pMemo}, this.mSysCodeGrpOperationCompleted, userState);
        }
        
        private void OnmSysCodeGrpOperationCompleted(object arg) {
            if ((this.mSysCodeGrpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mSysCodeGrpCompleted(this, new mSysCodeGrpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsSysCodeGrp/sSysCodeGrp_UsingFlag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sSysCodeGrp_UsingFlag([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pUsingFlag, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Memco.WebSvc.Sys.SysCode")] out DataSysCodeGrp[] reList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg) {
            object[] results = this.Invoke("sSysCodeGrp_UsingFlag", new object[] {
                        pUsingFlag});
            reList = ((DataSysCodeGrp[])(results[1]));
            reMsg = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sSysCodeGrp_UsingFlagAsync(string pUsingFlag) {
            this.sSysCodeGrp_UsingFlagAsync(pUsingFlag, null);
        }
        
        /// <remarks/>
        public void sSysCodeGrp_UsingFlagAsync(string pUsingFlag, object userState) {
            if ((this.sSysCodeGrp_UsingFlagOperationCompleted == null)) {
                this.sSysCodeGrp_UsingFlagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsSysCodeGrp_UsingFlagOperationCompleted);
            }
            this.InvokeAsync("sSysCodeGrp_UsingFlag", new object[] {
                        pUsingFlag}, this.sSysCodeGrp_UsingFlagOperationCompleted, userState);
        }
        
        private void OnsSysCodeGrp_UsingFlagOperationCompleted(object arg) {
            if ((this.sSysCodeGrp_UsingFlagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sSysCodeGrp_UsingFlagCompleted(this, new sSysCodeGrp_UsingFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsSysCodeGrp/sSysCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sSysCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScodeGrp, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pUsingFlag, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScodeNm, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Memco.WebSvc.Sys.SysCode")] out DataSysCode[] reList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg) {
            object[] results = this.Invoke("sSysCode", new object[] {
                        pScodeGrp,
                        pUsingFlag,
                        pScodeNm});
            reList = ((DataSysCode[])(results[1]));
            reMsg = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sSysCodeAsync(string pScodeGrp, string pUsingFlag, string pScodeNm) {
            this.sSysCodeAsync(pScodeGrp, pUsingFlag, pScodeNm, null);
        }
        
        /// <remarks/>
        public void sSysCodeAsync(string pScodeGrp, string pUsingFlag, string pScodeNm, object userState) {
            if ((this.sSysCodeOperationCompleted == null)) {
                this.sSysCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsSysCodeOperationCompleted);
            }
            this.InvokeAsync("sSysCode", new object[] {
                        pScodeGrp,
                        pUsingFlag,
                        pScodeNm}, this.sSysCodeOperationCompleted, userState);
        }
        
        private void OnsSysCodeOperationCompleted(object arg) {
            if ((this.sSysCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sSysCodeCompleted(this, new sSysCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsSysCodeGrp/mSysCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mSysCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScodeNm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pUsingFlag, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pSortNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pMemo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("mSysCode", new object[] {
                        pScode,
                        pScodeNm,
                        pUsingFlag,
                        pSortNo,
                        pMemo});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void mSysCodeAsync(string pScode, string pScodeNm, string pUsingFlag, string pSortNo, string pMemo) {
            this.mSysCodeAsync(pScode, pScodeNm, pUsingFlag, pSortNo, pMemo, null);
        }
        
        /// <remarks/>
        public void mSysCodeAsync(string pScode, string pScodeNm, string pUsingFlag, string pSortNo, string pMemo, object userState) {
            if ((this.mSysCodeOperationCompleted == null)) {
                this.mSysCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmSysCodeOperationCompleted);
            }
            this.InvokeAsync("mSysCode", new object[] {
                        pScode,
                        pScodeNm,
                        pUsingFlag,
                        pSortNo,
                        pMemo}, this.mSysCodeOperationCompleted, userState);
        }
        
        private void OnmSysCodeOperationCompleted(object arg) {
            if ((this.mSysCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mSysCodeCompleted(this, new mSysCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsSysCodeGrp/exSysCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string exSysCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("exSysCode", new object[] {
                        pScode});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void exSysCodeAsync(string pScode) {
            this.exSysCodeAsync(pScode, null);
        }
        
        /// <remarks/>
        public void exSysCodeAsync(string pScode, object userState) {
            if ((this.exSysCodeOperationCompleted == null)) {
                this.exSysCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexSysCodeOperationCompleted);
            }
            this.InvokeAsync("exSysCode", new object[] {
                        pScode}, this.exSysCodeOperationCompleted, userState);
        }
        
        private void OnexSysCodeOperationCompleted(object arg) {
            if ((this.exSysCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exSysCodeCompleted(this, new exSysCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsSysCodeGrp/aSysCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string aSysCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScodeGrp, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScodeNm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pUsingFlag, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pMemo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pSortNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pInputId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("aSysCode", new object[] {
                        pScode,
                        pScodeGrp,
                        pScodeNm,
                        pUsingFlag,
                        pMemo,
                        pSortNo,
                        pInputId});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aSysCodeAsync(string pScode, string pScodeGrp, string pScodeNm, string pUsingFlag, string pMemo, string pSortNo, string pInputId) {
            this.aSysCodeAsync(pScode, pScodeGrp, pScodeNm, pUsingFlag, pMemo, pSortNo, pInputId, null);
        }
        
        /// <remarks/>
        public void aSysCodeAsync(string pScode, string pScodeGrp, string pScodeNm, string pUsingFlag, string pMemo, string pSortNo, string pInputId, object userState) {
            if ((this.aSysCodeOperationCompleted == null)) {
                this.aSysCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaSysCodeOperationCompleted);
            }
            this.InvokeAsync("aSysCode", new object[] {
                        pScode,
                        pScodeGrp,
                        pScodeNm,
                        pUsingFlag,
                        pMemo,
                        pSortNo,
                        pInputId}, this.aSysCodeOperationCompleted, userState);
        }
        
        private void OnaSysCodeOperationCompleted(object arg) {
            if ((this.aSysCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aSysCodeCompleted(this, new aSysCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsSysCodeGrp/fSysCodeSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fSysCodeSearch([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _scodeGrp, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pScode_Nm, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Memco.WebSvc.Sys.SysCode")] out DataSysCode[] reList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg) {
            object[] results = this.Invoke("fSysCodeSearch", new object[] {
                        _scodeGrp,
                        pScode_Nm});
            reList = ((DataSysCode[])(results[1]));
            reMsg = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fSysCodeSearchAsync(string _scodeGrp, string pScode_Nm) {
            this.fSysCodeSearchAsync(_scodeGrp, pScode_Nm, null);
        }
        
        /// <remarks/>
        public void fSysCodeSearchAsync(string _scodeGrp, string pScode_Nm, object userState) {
            if ((this.fSysCodeSearchOperationCompleted == null)) {
                this.fSysCodeSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfSysCodeSearchOperationCompleted);
            }
            this.InvokeAsync("fSysCodeSearch", new object[] {
                        _scodeGrp,
                        pScode_Nm}, this.fSysCodeSearchOperationCompleted, userState);
        }
        
        private void OnfSysCodeSearchOperationCompleted(object arg) {
            if ((this.fSysCodeSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fSysCodeSearchCompleted(this, new fSysCodeSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Memco.WebSvc.Sys.SysCode")]
    public partial class DataSysCodeGrp {
        
        private string sCODE_GRPField;
        
        private string sCODE_NMField;
        
        private int uSING_FLAGField;
        
        private bool uSING_FLAGFieldSpecified;
        
        private int sORT_NOField;
        
        private bool sORT_NOFieldSpecified;
        
        private string mEMOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SCODE_GRP {
            get {
                return this.sCODE_GRPField;
            }
            set {
                this.sCODE_GRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SCODE_NM {
            get {
                return this.sCODE_NMField;
            }
            set {
                this.sCODE_NMField = value;
            }
        }
        
        /// <remarks/>
        public int USING_FLAG {
            get {
                return this.uSING_FLAGField;
            }
            set {
                this.uSING_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USING_FLAGSpecified {
            get {
                return this.uSING_FLAGFieldSpecified;
            }
            set {
                this.uSING_FLAGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SORT_NO {
            get {
                return this.sORT_NOField;
            }
            set {
                this.sORT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SORT_NOSpecified {
            get {
                return this.sORT_NOFieldSpecified;
            }
            set {
                this.sORT_NOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MEMO {
            get {
                return this.mEMOField;
            }
            set {
                this.mEMOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Memco.WebSvc.Sys.SysCode")]
    public partial class DataSysCode {
        
        private string sCODEField;
        
        private string sCODE_NMField;
        
        private int uSING_FLAGField;
        
        private bool uSING_FLAGFieldSpecified;
        
        private int sORT_NOField;
        
        private bool sORT_NOFieldSpecified;
        
        private string mEMOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SCODE {
            get {
                return this.sCODEField;
            }
            set {
                this.sCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SCODE_NM {
            get {
                return this.sCODE_NMField;
            }
            set {
                this.sCODE_NMField = value;
            }
        }
        
        /// <remarks/>
        public int USING_FLAG {
            get {
                return this.uSING_FLAGField;
            }
            set {
                this.uSING_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USING_FLAGSpecified {
            get {
                return this.uSING_FLAGFieldSpecified;
            }
            set {
                this.uSING_FLAGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SORT_NO {
            get {
                return this.sORT_NOField;
            }
            set {
                this.sORT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SORT_NOSpecified {
            get {
                return this.sORT_NOFieldSpecified;
            }
            set {
                this.sORT_NOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MEMO {
            get {
                return this.mEMOField;
            }
            set {
                this.mEMOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sSysCodeGrpCompletedEventHandler(object sender, sSysCodeGrpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sSysCodeGrpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sSysCodeGrpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DataSysCodeGrp[] reList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataSysCodeGrp[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void mSysCodeGrpCompletedEventHandler(object sender, mSysCodeGrpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mSysCodeGrpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mSysCodeGrpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public bool reDataSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sSysCodeGrp_UsingFlagCompletedEventHandler(object sender, sSysCodeGrp_UsingFlagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sSysCodeGrp_UsingFlagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sSysCodeGrp_UsingFlagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DataSysCodeGrp[] reList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataSysCodeGrp[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sSysCodeCompletedEventHandler(object sender, sSysCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sSysCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sSysCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DataSysCode[] reList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataSysCode[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void mSysCodeCompletedEventHandler(object sender, mSysCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mSysCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mSysCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void exSysCodeCompletedEventHandler(object sender, exSysCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exSysCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exSysCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void aSysCodeCompletedEventHandler(object sender, aSysCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aSysCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aSysCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void fSysCodeSearchCompletedEventHandler(object sender, fSysCodeSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fSysCodeSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fSysCodeSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DataSysCode[] reList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataSysCode[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591