//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EldigmPlusApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49469/WebSvc/Sys/ComnCode/WsComnCodeGrp.svc")]
        public string EldigmPlusApp_WsCCodeGrp_WsComnCodeGrp {
            get {
                return ((string)(this["EldigmPlusApp_WsCCodeGrp_WsComnCodeGrp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49501/WebSvc/MainHome/WsMainHome.svc")]
        public string EldigmPlusApp_Mem_WsMHome_WsMainHome {
            get {
                return ((string)(this["EldigmPlusApp_Mem_WsMHome_WsMainHome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49469/WebSvc/Sys/SysCode/WsSysCodeGrp.svc")]
        public string EldigmPlusApp_WsSCodeGrp_WsSysCodeGrp {
            get {
                return ((string)(this["EldigmPlusApp_WsSCodeGrp_WsSysCodeGrp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49469/WebSvc/Sys/SysAuth/WsSysAuthMainDB.svc")]
        public string EldigmPlusApp_WsSAuthMainDB_WsSysAuthMainDB {
            get {
                return ((string)(this["EldigmPlusApp_WsSAuthMainDB_WsSysAuthMainDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49501/WebSvc/MainHome/WsMainHome.svc")]
        public string EldigmPlusApp_WsMHome_WsMainHome {
            get {
                return ((string)(this["EldigmPlusApp_WsMHome_WsMainHome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49469/WebSvc/Sys/Menu/WsMenuMainDB.svc")]
        public string EldigmPlusApp_M_WsMenuMainDB_WsMenuMainDB {
            get {
                return ((string)(this["EldigmPlusApp_M_WsMenuMainDB_WsMenuMainDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49501/WebSvc/Sys/SysAuth/WsSysAuthMemberDB.svc")]
        public string EldigmPlusApp_Mem_WsSysAuthMemberDB_WsSysAuthMemberDB {
            get {
                return ((string)(this["EldigmPlusApp_Mem_WsSysAuthMemberDB_WsSysAuthMemberDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49501/WebSvc/Sys/SysAuth/WsSysAuthMemberDB.svc")]
        public string EldigmPlusApp_Mem_WsSysAuthMemberDB_WsSysAuthMemberDB1 {
            get {
                return ((string)(this["EldigmPlusApp_Mem_WsSysAuthMemberDB_WsSysAuthMemberDB1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49469/WebSvc/Sys/MemberSite/WsMember.svc")]
        public string EldigmPlusApp_M_WsMember_WsMember {
            get {
                return ((string)(this["EldigmPlusApp_M_WsMember_WsMember"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49501/WebSvc/Sys/CompanyTeam/WsSysCompanyTeam.svc")]
        public string EldigmPlusApp_Mem_WsSysCompanyTeam_WsSysCompanyTeam {
            get {
                return ((string)(this["EldigmPlusApp_Mem_WsSysCompanyTeam_WsSysCompanyTeam"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49469/WebSvc/Sys/CodeT/WsCodeTMainDB.svc")]
        public string EldigmPlusApp_M_WsCodeTMainDB_WsCodeTMainDB {
            get {
                return ((string)(this["EldigmPlusApp_M_WsCodeTMainDB_WsCodeTMainDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49469/WebSvc/Worker/InOut/WsInOut.svc")]
        public string EldigmPlusApp_Mem_WsInOut_WsInOut {
            get {
                return ((string)(this["EldigmPlusApp_Mem_WsInOut_WsInOut"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49501/WebSvc/Sys/Device/WsDevice.svc")]
        public string EldigmPlusApp_Mem_WsDevice_WsDevice {
            get {
                return ((string)(this["EldigmPlusApp_Mem_WsDevice_WsDevice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49501/WebSvc/Worker/Labor/WsWorkerLaborSearch.svc")]
        public string EldigmPlusApp_Mem_WsWorkerLaborSearch_WsWorkerLaborSearch {
            get {
                return ((string)(this["EldigmPlusApp_Mem_WsWorkerLaborSearch_WsWorkerLaborSearch"]));
            }
        }
    }
}
