//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace EldigmPlusApp.M_WsMenuMainDB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWsMenuMainDB", Namespace="http://tempuri.org/")]
    public partial class WsMenuMainDB : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sManuTopTreeViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback sManuSubTreeViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback sManuTreeViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback sManuTreeView2OperationCompleted;
        
        private System.Threading.SendOrPostCallback exMenuTopOperationCompleted;
        
        private System.Threading.SendOrPostCallback exMenuSubOperationCompleted;
        
        private System.Threading.SendOrPostCallback exMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback aMenuTopOperationCompleted;
        
        private System.Threading.SendOrPostCallback aMenuSubOperationCompleted;
        
        private System.Threading.SendOrPostCallback aMenuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsMenuMainDB() {
            this.Url = global::EldigmPlusApp.Properties.Settings.Default.EldigmPlusApp_M_WsMenuMainDB_WsMenuMainDB;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sManuTopTreeViewCompletedEventHandler sManuTopTreeViewCompleted;
        
        /// <remarks/>
        public event sManuSubTreeViewCompletedEventHandler sManuSubTreeViewCompleted;
        
        /// <remarks/>
        public event sManuTreeViewCompletedEventHandler sManuTreeViewCompleted;
        
        /// <remarks/>
        public event sManuTreeView2CompletedEventHandler sManuTreeView2Completed;
        
        /// <remarks/>
        public event exMenuTopCompletedEventHandler exMenuTopCompleted;
        
        /// <remarks/>
        public event exMenuSubCompletedEventHandler exMenuSubCompleted;
        
        /// <remarks/>
        public event exMenuCompletedEventHandler exMenuCompleted;
        
        /// <remarks/>
        public event aMenuTopCompletedEventHandler aMenuTopCompleted;
        
        /// <remarks/>
        public event aMenuSubCompletedEventHandler aMenuSubCompleted;
        
        /// <remarks/>
        public event aMenuCompletedEventHandler aMenuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/sManuTopTreeView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sManuTopTreeView([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string USING_FLAG, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Main.WebSvc.Sys.Menu")] out DataMenuTop[] reList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg) {
            object[] results = this.Invoke("sManuTopTreeView", new object[] {
                        USING_FLAG});
            reList = ((DataMenuTop[])(results[1]));
            reMsg = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sManuTopTreeViewAsync(string USING_FLAG) {
            this.sManuTopTreeViewAsync(USING_FLAG, null);
        }
        
        /// <remarks/>
        public void sManuTopTreeViewAsync(string USING_FLAG, object userState) {
            if ((this.sManuTopTreeViewOperationCompleted == null)) {
                this.sManuTopTreeViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsManuTopTreeViewOperationCompleted);
            }
            this.InvokeAsync("sManuTopTreeView", new object[] {
                        USING_FLAG}, this.sManuTopTreeViewOperationCompleted, userState);
        }
        
        private void OnsManuTopTreeViewOperationCompleted(object arg) {
            if ((this.sManuTopTreeViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sManuTopTreeViewCompleted(this, new sManuTopTreeViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/sManuSubTreeView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sManuSubTreeView([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string USING_FLAG, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Main.WebSvc.Sys.Menu")] out DataMenuSub[] reList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg) {
            object[] results = this.Invoke("sManuSubTreeView", new object[] {
                        TOP_MENU_CD,
                        USING_FLAG});
            reList = ((DataMenuSub[])(results[1]));
            reMsg = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sManuSubTreeViewAsync(string TOP_MENU_CD, string USING_FLAG) {
            this.sManuSubTreeViewAsync(TOP_MENU_CD, USING_FLAG, null);
        }
        
        /// <remarks/>
        public void sManuSubTreeViewAsync(string TOP_MENU_CD, string USING_FLAG, object userState) {
            if ((this.sManuSubTreeViewOperationCompleted == null)) {
                this.sManuSubTreeViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsManuSubTreeViewOperationCompleted);
            }
            this.InvokeAsync("sManuSubTreeView", new object[] {
                        TOP_MENU_CD,
                        USING_FLAG}, this.sManuSubTreeViewOperationCompleted, userState);
        }
        
        private void OnsManuSubTreeViewOperationCompleted(object arg) {
            if ((this.sManuSubTreeViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sManuSubTreeViewCompleted(this, new sManuSubTreeViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/sManuTreeView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sManuTreeView([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SUB_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string USING_FLAG, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Main.WebSvc.Sys.Menu")] out DataMenu[] reList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg) {
            object[] results = this.Invoke("sManuTreeView", new object[] {
                        TOP_MENU_CD,
                        SUB_MENU_CD,
                        USING_FLAG});
            reList = ((DataMenu[])(results[1]));
            reMsg = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sManuTreeViewAsync(string TOP_MENU_CD, string SUB_MENU_CD, string USING_FLAG) {
            this.sManuTreeViewAsync(TOP_MENU_CD, SUB_MENU_CD, USING_FLAG, null);
        }
        
        /// <remarks/>
        public void sManuTreeViewAsync(string TOP_MENU_CD, string SUB_MENU_CD, string USING_FLAG, object userState) {
            if ((this.sManuTreeViewOperationCompleted == null)) {
                this.sManuTreeViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsManuTreeViewOperationCompleted);
            }
            this.InvokeAsync("sManuTreeView", new object[] {
                        TOP_MENU_CD,
                        SUB_MENU_CD,
                        USING_FLAG}, this.sManuTreeViewOperationCompleted, userState);
        }
        
        private void OnsManuTreeViewOperationCompleted(object arg) {
            if ((this.sManuTreeViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sManuTreeViewCompleted(this, new sManuTreeViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/sManuTreeView2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sManuTreeView2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SUB_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string USING_FLAG, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Main.WebSvc.Sys.Menu")] out DataMenu[] reList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg) {
            object[] results = this.Invoke("sManuTreeView2", new object[] {
                        TOP_MENU_CD,
                        SUB_MENU_CD,
                        MENU_CD,
                        USING_FLAG});
            reList = ((DataMenu[])(results[1]));
            reMsg = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sManuTreeView2Async(string TOP_MENU_CD, string SUB_MENU_CD, string MENU_CD, string USING_FLAG) {
            this.sManuTreeView2Async(TOP_MENU_CD, SUB_MENU_CD, MENU_CD, USING_FLAG, null);
        }
        
        /// <remarks/>
        public void sManuTreeView2Async(string TOP_MENU_CD, string SUB_MENU_CD, string MENU_CD, string USING_FLAG, object userState) {
            if ((this.sManuTreeView2OperationCompleted == null)) {
                this.sManuTreeView2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnsManuTreeView2OperationCompleted);
            }
            this.InvokeAsync("sManuTreeView2", new object[] {
                        TOP_MENU_CD,
                        SUB_MENU_CD,
                        MENU_CD,
                        USING_FLAG}, this.sManuTreeView2OperationCompleted, userState);
        }
        
        private void OnsManuTreeView2OperationCompleted(object arg) {
            if ((this.sManuTreeView2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sManuTreeView2Completed(this, new sManuTreeView2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/exMenuTop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string exMenuTop([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_NM, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("exMenuTop", new object[] {
                        TOP_MENU_CD,
                        TOP_MENU_NM});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void exMenuTopAsync(string TOP_MENU_CD, string TOP_MENU_NM) {
            this.exMenuTopAsync(TOP_MENU_CD, TOP_MENU_NM, null);
        }
        
        /// <remarks/>
        public void exMenuTopAsync(string TOP_MENU_CD, string TOP_MENU_NM, object userState) {
            if ((this.exMenuTopOperationCompleted == null)) {
                this.exMenuTopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexMenuTopOperationCompleted);
            }
            this.InvokeAsync("exMenuTop", new object[] {
                        TOP_MENU_CD,
                        TOP_MENU_NM}, this.exMenuTopOperationCompleted, userState);
        }
        
        private void OnexMenuTopOperationCompleted(object arg) {
            if ((this.exMenuTopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exMenuTopCompleted(this, new exMenuTopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/exMenuSub", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string exMenuSub([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SUB_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SUB_MENU_NM, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("exMenuSub", new object[] {
                        SUB_MENU_CD,
                        TOP_MENU_CD,
                        SUB_MENU_NM});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void exMenuSubAsync(string SUB_MENU_CD, string TOP_MENU_CD, string SUB_MENU_NM) {
            this.exMenuSubAsync(SUB_MENU_CD, TOP_MENU_CD, SUB_MENU_NM, null);
        }
        
        /// <remarks/>
        public void exMenuSubAsync(string SUB_MENU_CD, string TOP_MENU_CD, string SUB_MENU_NM, object userState) {
            if ((this.exMenuSubOperationCompleted == null)) {
                this.exMenuSubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexMenuSubOperationCompleted);
            }
            this.InvokeAsync("exMenuSub", new object[] {
                        SUB_MENU_CD,
                        TOP_MENU_CD,
                        SUB_MENU_NM}, this.exMenuSubOperationCompleted, userState);
        }
        
        private void OnexMenuSubOperationCompleted(object arg) {
            if ((this.exMenuSubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exMenuSubCompleted(this, new exMenuSubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/exMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string exMenu([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SUB_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string MENU_NM, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("exMenu", new object[] {
                        MENU_CD,
                        TOP_MENU_CD,
                        SUB_MENU_CD,
                        MENU_NM});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void exMenuAsync(string MENU_CD, string TOP_MENU_CD, string SUB_MENU_CD, string MENU_NM) {
            this.exMenuAsync(MENU_CD, TOP_MENU_CD, SUB_MENU_CD, MENU_NM, null);
        }
        
        /// <remarks/>
        public void exMenuAsync(string MENU_CD, string TOP_MENU_CD, string SUB_MENU_CD, string MENU_NM, object userState) {
            if ((this.exMenuOperationCompleted == null)) {
                this.exMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexMenuOperationCompleted);
            }
            this.InvokeAsync("exMenu", new object[] {
                        MENU_CD,
                        TOP_MENU_CD,
                        SUB_MENU_CD,
                        MENU_NM}, this.exMenuOperationCompleted, userState);
        }
        
        private void OnexMenuOperationCompleted(object arg) {
            if ((this.exMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exMenuCompleted(this, new exMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/aMenuTop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string aMenuTop([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_NM, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string APP_FLAG, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string USING_FLAG, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SORT_NO, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string INPUT_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("aMenuTop", new object[] {
                        TOP_MENU_NM,
                        APP_FLAG,
                        USING_FLAG,
                        SORT_NO,
                        INPUT_ID});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aMenuTopAsync(string TOP_MENU_NM, string APP_FLAG, string USING_FLAG, string SORT_NO, string INPUT_ID) {
            this.aMenuTopAsync(TOP_MENU_NM, APP_FLAG, USING_FLAG, SORT_NO, INPUT_ID, null);
        }
        
        /// <remarks/>
        public void aMenuTopAsync(string TOP_MENU_NM, string APP_FLAG, string USING_FLAG, string SORT_NO, string INPUT_ID, object userState) {
            if ((this.aMenuTopOperationCompleted == null)) {
                this.aMenuTopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaMenuTopOperationCompleted);
            }
            this.InvokeAsync("aMenuTop", new object[] {
                        TOP_MENU_NM,
                        APP_FLAG,
                        USING_FLAG,
                        SORT_NO,
                        INPUT_ID}, this.aMenuTopOperationCompleted, userState);
        }
        
        private void OnaMenuTopOperationCompleted(object arg) {
            if ((this.aMenuTopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aMenuTopCompleted(this, new aMenuTopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/aMenuSub", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string aMenuSub([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SUB_MENU_NM, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string USING_FLAG, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SORT_NO, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string INPUT_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("aMenuSub", new object[] {
                        TOP_MENU_CD,
                        SUB_MENU_NM,
                        USING_FLAG,
                        SORT_NO,
                        INPUT_ID});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aMenuSubAsync(string TOP_MENU_CD, string SUB_MENU_NM, string USING_FLAG, string SORT_NO, string INPUT_ID) {
            this.aMenuSubAsync(TOP_MENU_CD, SUB_MENU_NM, USING_FLAG, SORT_NO, INPUT_ID, null);
        }
        
        /// <remarks/>
        public void aMenuSubAsync(string TOP_MENU_CD, string SUB_MENU_NM, string USING_FLAG, string SORT_NO, string INPUT_ID, object userState) {
            if ((this.aMenuSubOperationCompleted == null)) {
                this.aMenuSubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaMenuSubOperationCompleted);
            }
            this.InvokeAsync("aMenuSub", new object[] {
                        TOP_MENU_CD,
                        SUB_MENU_NM,
                        USING_FLAG,
                        SORT_NO,
                        INPUT_ID}, this.aMenuSubOperationCompleted, userState);
        }
        
        private void OnaMenuSubOperationCompleted(object arg) {
            if ((this.aMenuSubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aMenuSubCompleted(this, new aMenuSubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWsMenuMainDB/aMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string aMenu([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TOP_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SUB_MENU_CD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string MENU_NM, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string USING_FLAG, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SORT_NO, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string INPUT_ID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reMsg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string reData) {
            object[] results = this.Invoke("aMenu", new object[] {
                        MENU_CD,
                        TOP_MENU_CD,
                        SUB_MENU_CD,
                        MENU_NM,
                        USING_FLAG,
                        SORT_NO,
                        INPUT_ID});
            reMsg = ((string)(results[1]));
            reData = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aMenuAsync(string MENU_CD, string TOP_MENU_CD, string SUB_MENU_CD, string MENU_NM, string USING_FLAG, string SORT_NO, string INPUT_ID) {
            this.aMenuAsync(MENU_CD, TOP_MENU_CD, SUB_MENU_CD, MENU_NM, USING_FLAG, SORT_NO, INPUT_ID, null);
        }
        
        /// <remarks/>
        public void aMenuAsync(string MENU_CD, string TOP_MENU_CD, string SUB_MENU_CD, string MENU_NM, string USING_FLAG, string SORT_NO, string INPUT_ID, object userState) {
            if ((this.aMenuOperationCompleted == null)) {
                this.aMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaMenuOperationCompleted);
            }
            this.InvokeAsync("aMenu", new object[] {
                        MENU_CD,
                        TOP_MENU_CD,
                        SUB_MENU_CD,
                        MENU_NM,
                        USING_FLAG,
                        SORT_NO,
                        INPUT_ID}, this.aMenuOperationCompleted, userState);
        }
        
        private void OnaMenuOperationCompleted(object arg) {
            if ((this.aMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aMenuCompleted(this, new aMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Main.WebSvc.Sys.Menu")]
    public partial class DataMenuTop {
        
        private int tOP_MENU_CDField;
        
        private bool tOP_MENU_CDFieldSpecified;
        
        private string tOP_MENU_NMField;
        
        private int aPP_FLAGField;
        
        private bool aPP_FLAGFieldSpecified;
        
        private int uSING_FLAGField;
        
        private bool uSING_FLAGFieldSpecified;
        
        private int sORT_NOField;
        
        private bool sORT_NOFieldSpecified;
        
        /// <remarks/>
        public int TOP_MENU_CD {
            get {
                return this.tOP_MENU_CDField;
            }
            set {
                this.tOP_MENU_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOP_MENU_CDSpecified {
            get {
                return this.tOP_MENU_CDFieldSpecified;
            }
            set {
                this.tOP_MENU_CDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TOP_MENU_NM {
            get {
                return this.tOP_MENU_NMField;
            }
            set {
                this.tOP_MENU_NMField = value;
            }
        }
        
        /// <remarks/>
        public int APP_FLAG {
            get {
                return this.aPP_FLAGField;
            }
            set {
                this.aPP_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool APP_FLAGSpecified {
            get {
                return this.aPP_FLAGFieldSpecified;
            }
            set {
                this.aPP_FLAGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int USING_FLAG {
            get {
                return this.uSING_FLAGField;
            }
            set {
                this.uSING_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USING_FLAGSpecified {
            get {
                return this.uSING_FLAGFieldSpecified;
            }
            set {
                this.uSING_FLAGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SORT_NO {
            get {
                return this.sORT_NOField;
            }
            set {
                this.sORT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SORT_NOSpecified {
            get {
                return this.sORT_NOFieldSpecified;
            }
            set {
                this.sORT_NOFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Main.WebSvc.Sys.Menu")]
    public partial class DataMenu {
        
        private string mENU_CDField;
        
        private int tOP_MENU_CDField;
        
        private bool tOP_MENU_CDFieldSpecified;
        
        private int sUB_MENU_CDField;
        
        private bool sUB_MENU_CDFieldSpecified;
        
        private string mENU_NMField;
        
        private int uSING_FLAGField;
        
        private bool uSING_FLAGFieldSpecified;
        
        private int sORT_NOField;
        
        private bool sORT_NOFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MENU_CD {
            get {
                return this.mENU_CDField;
            }
            set {
                this.mENU_CDField = value;
            }
        }
        
        /// <remarks/>
        public int TOP_MENU_CD {
            get {
                return this.tOP_MENU_CDField;
            }
            set {
                this.tOP_MENU_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOP_MENU_CDSpecified {
            get {
                return this.tOP_MENU_CDFieldSpecified;
            }
            set {
                this.tOP_MENU_CDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SUB_MENU_CD {
            get {
                return this.sUB_MENU_CDField;
            }
            set {
                this.sUB_MENU_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUB_MENU_CDSpecified {
            get {
                return this.sUB_MENU_CDFieldSpecified;
            }
            set {
                this.sUB_MENU_CDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MENU_NM {
            get {
                return this.mENU_NMField;
            }
            set {
                this.mENU_NMField = value;
            }
        }
        
        /// <remarks/>
        public int USING_FLAG {
            get {
                return this.uSING_FLAGField;
            }
            set {
                this.uSING_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USING_FLAGSpecified {
            get {
                return this.uSING_FLAGFieldSpecified;
            }
            set {
                this.uSING_FLAGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SORT_NO {
            get {
                return this.sORT_NOField;
            }
            set {
                this.sORT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SORT_NOSpecified {
            get {
                return this.sORT_NOFieldSpecified;
            }
            set {
                this.sORT_NOFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EldigmPlusSvc_Main.WebSvc.Sys.Menu")]
    public partial class DataMenuSub {
        
        private int sUB_MENU_CDField;
        
        private bool sUB_MENU_CDFieldSpecified;
        
        private int tOP_MENU_CDField;
        
        private bool tOP_MENU_CDFieldSpecified;
        
        private string sUB_MENU_NMField;
        
        private int uSING_FLAGField;
        
        private bool uSING_FLAGFieldSpecified;
        
        private int sORT_NOField;
        
        private bool sORT_NOFieldSpecified;
        
        /// <remarks/>
        public int SUB_MENU_CD {
            get {
                return this.sUB_MENU_CDField;
            }
            set {
                this.sUB_MENU_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUB_MENU_CDSpecified {
            get {
                return this.sUB_MENU_CDFieldSpecified;
            }
            set {
                this.sUB_MENU_CDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TOP_MENU_CD {
            get {
                return this.tOP_MENU_CDField;
            }
            set {
                this.tOP_MENU_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOP_MENU_CDSpecified {
            get {
                return this.tOP_MENU_CDFieldSpecified;
            }
            set {
                this.tOP_MENU_CDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SUB_MENU_NM {
            get {
                return this.sUB_MENU_NMField;
            }
            set {
                this.sUB_MENU_NMField = value;
            }
        }
        
        /// <remarks/>
        public int USING_FLAG {
            get {
                return this.uSING_FLAGField;
            }
            set {
                this.uSING_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USING_FLAGSpecified {
            get {
                return this.uSING_FLAGFieldSpecified;
            }
            set {
                this.uSING_FLAGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SORT_NO {
            get {
                return this.sORT_NOField;
            }
            set {
                this.sORT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SORT_NOSpecified {
            get {
                return this.sORT_NOFieldSpecified;
            }
            set {
                this.sORT_NOFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sManuTopTreeViewCompletedEventHandler(object sender, sManuTopTreeViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sManuTopTreeViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sManuTopTreeViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DataMenuTop[] reList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataMenuTop[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sManuSubTreeViewCompletedEventHandler(object sender, sManuSubTreeViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sManuSubTreeViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sManuSubTreeViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DataMenuSub[] reList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataMenuSub[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sManuTreeViewCompletedEventHandler(object sender, sManuTreeViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sManuTreeViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sManuTreeViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DataMenu[] reList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataMenu[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sManuTreeView2CompletedEventHandler(object sender, sManuTreeView2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sManuTreeView2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sManuTreeView2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public DataMenu[] reList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataMenu[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void exMenuTopCompletedEventHandler(object sender, exMenuTopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exMenuTopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exMenuTopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void exMenuSubCompletedEventHandler(object sender, exMenuSubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exMenuSubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exMenuSubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void exMenuCompletedEventHandler(object sender, exMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void aMenuTopCompletedEventHandler(object sender, aMenuTopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aMenuTopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aMenuTopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void aMenuSubCompletedEventHandler(object sender, aMenuSubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aMenuSubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aMenuSubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void aMenuCompletedEventHandler(object sender, aMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string reMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string reData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591